services:
  - type: web
    name: labnova-backend
    runtime: docker
    plan: free
    rootDir: backend-lab-nova
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: LabNova
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: labnova-db
          property: connectionString
      - key: APP_URL
        value: https://labnova-backend.onrender.com
      - key: FILESYSTEM_DISK
        value: cloudinary
      - key: CLOUDINARY_URL
        value: cloudinary://715332765746538:AwCcGJOcXwsOwjxON_xxxABAOtg@dsaftsoy4
      - key: CLOUDINARY_CLOUD_NAME
        value: dsaftsoy4
      - key: CLOUDINARY_API_KEY
        value: 715332765746538
      - key: CLOUDINARY_API_SECRET
        value: AwCcGJOcXwsOwjxON_xxxABAOtg
      - key: CORS_ALLOWED_ORIGINS
        value: "https://labnova.vercel.app"
    volumes:
      - path: /app/storage/app/public
        name: labnova-storage

databases:
  - name: labnova-db
    plan: free
    databaseName: labnova
    user: labnova_user